"""Phase 4 — Ensemble meta-model.

Takes the outputs of all three conviction layers as inputs and learns the
optimal blend from historical outcomes:
  - rule_conviction  : weighted sum of signal strengths (always available)
  - ml_conviction    : P(profitable) from GradientBoosting (0 if no model)
  - sentiment_score  : macro keyword score aligned to direction (0 if unavailable)

Output: a single conviction score in [0, 1].

Training data is generated by walking historical OHLCV and computing all three
inputs per bar, with the actual forward return as the label.  Because historical
sentiment is unavailable (NewsAPI free tier = 30 days), sentiment_score is 0 for
historical samples — but the model learns its weight from live data over time as
the opportunities table accumulates real sentiment outcomes.
"""
from __future__ import annotations

import logging
from functools import lru_cache
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from trading_copilot.signals.rules import detect_signals
from trading_copilot.signals.scorer import SIGNAL_WEIGHTS

logger = logging.getLogger(__name__)

DEFAULT_ENSEMBLE_PATH = "data/ensemble_model.joblib"

ENSEMBLE_FEATURE_NAMES = [
    "rule_conviction",
    "ml_conviction",
    "sentiment_aligned",   # sentiment score sign-adjusted to direction (+ve = agrees)
    "ml_available",        # binary: 1 if ML model was used
    "sentiment_available", # binary: 1 if sentiment was provided
]


def _rule_conviction(signals) -> tuple[float, str]:
    """Return (rule_conviction, direction) from raw signals."""
    raw = sum(SIGNAL_WEIGHTS.get(s.signal_type, 0) * s.strength for s in signals)
    direction = "buy" if raw >= 0 else "sell"
    return min(1.0, abs(raw)), direction


def build_ensemble_dataset(
    ohlcv_data: dict[str, pd.DataFrame],
    cfg: dict,
    forward_days: int = 10,
    ml_model_path: str | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate (X, y) for ensemble training from historical OHLCV."""
    from trading_copilot.signals.ml.predictor import predict_conviction, model_exists
    from trading_copilot.signals.ml.trainer import DEFAULT_MODEL_PATH

    model_path = ml_model_path or DEFAULT_MODEL_PATH
    has_ml = model_exists(model_path)
    if not has_ml:
        logger.warning("No ML model found at %s — ml_conviction will be 0", model_path)

    X_rows: list[list[float]] = []
    y_rows: list[int] = []

    for ticker, df in ohlcv_data.items():
        if df.empty or len(df) < 60 + forward_days:
            continue
        dates = sorted(df["date"].unique())

        for i in range(60, len(dates) - forward_days):
            window = df[df["date"] <= dates[i]].copy()
            signals = detect_signals(window, cfg)
            if not signals:
                continue

            rule_conv, direction = _rule_conviction(signals)

            buy_sigs = [s for s in signals if s.direction == "buy"]
            sell_sigs = [s for s in signals if s.direction == "sell"]
            aligned_sigs = buy_sigs if direction == "buy" else sell_sigs
            if len(aligned_sigs) < 2:
                continue

            # ML conviction
            if has_ml:
                ml_conv = predict_conviction(window, signals, cfg, model_path=model_path) or 0.0
                ml_avail = 1.0
            else:
                ml_conv = 0.0
                ml_avail = 0.0

            # Sentiment unavailable for historical data — use 0
            sentiment_aligned = 0.0
            sentiment_avail = 0.0

            # Label: was the direction correct over forward_days?
            entry_price = float(window["adj_close"].iloc[-1])
            future_row = df[df["date"] == dates[i + forward_days]]
            if future_row.empty:
                continue
            exit_price = float(future_row["adj_close"].iloc[0])
            fwd_return = (exit_price - entry_price) / entry_price
            label = 1 if (
                (direction == "buy" and fwd_return > 0) or
                (direction == "sell" and fwd_return < 0)
            ) else 0

            X_rows.append([rule_conv, ml_conv, sentiment_aligned, ml_avail, sentiment_avail])
            y_rows.append(label)

    if not X_rows:
        raise ValueError("No ensemble training samples generated.")

    X = np.array(X_rows, dtype=np.float32)
    y = np.array(y_rows, dtype=np.int32)
    logger.info("Ensemble dataset: %d samples, %.1f%% positive", len(y), y.mean() * 100)
    return X, y


def train_ensemble(
    ohlcv_data: dict[str, pd.DataFrame],
    cfg: dict,
    forward_days: int = 10,
    ml_model_path: str | None = None,
    ensemble_path: str = DEFAULT_ENSEMBLE_PATH,
) -> tuple[Pipeline, np.ndarray]:
    """Train and save the ensemble meta-model."""
    X, y = build_ensemble_dataset(ohlcv_data, cfg, forward_days, ml_model_path)

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(C=1.0, max_iter=1000, random_state=42)),
    ])

    cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring="roc_auc")
    logger.info("Ensemble CV ROC-AUC: %.3f ± %.3f", cv_scores.mean(), cv_scores.std())

    pipeline.fit(X, y)

    # Log learned weights for interpretability
    coef = pipeline.named_steps["clf"].coef_[0]
    for name, weight in zip(ENSEMBLE_FEATURE_NAMES, coef):
        logger.info("  %-22s weight=%.4f", name, weight)

    Path(ensemble_path).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"pipeline": pipeline, "feature_names": ENSEMBLE_FEATURE_NAMES}, ensemble_path)
    logger.info("Ensemble model saved → %s", ensemble_path)
    return pipeline, cv_scores


@lru_cache(maxsize=1)
def _load_ensemble(path: str) -> dict | None:
    if not Path(path).exists():
        return None
    return joblib.load(path)


def ensemble_exists(path: str = DEFAULT_ENSEMBLE_PATH) -> bool:
    return Path(path).exists()


def invalidate_cache() -> None:
    _load_ensemble.cache_clear()


def predict_ensemble(
    rule_conviction: float,
    ml_conviction: float | None,
    sentiment_score: float | None,
    direction: str,
    ensemble_path: str = DEFAULT_ENSEMBLE_PATH,
) -> float | None:
    """Return ensemble P(profitable) or None if no model loaded."""
    bundle = _load_ensemble(ensemble_path)
    if bundle is None:
        return None

    ml_conv = ml_conviction if ml_conviction is not None else 0.0
    ml_avail = 1.0 if ml_conviction is not None else 0.0

    direction_sign = 1.0 if direction == "buy" else -1.0
    if sentiment_score is not None:
        sent_aligned = sentiment_score * direction_sign
        sent_avail = 1.0
    else:
        sent_aligned = 0.0
        sent_avail = 0.0

    vec = np.array([[rule_conviction, ml_conv, sent_aligned, ml_avail, sent_avail]], dtype=np.float32)
    try:
        return float(bundle["pipeline"].predict_proba(vec)[0][1])
    except Exception as exc:
        logger.warning("Ensemble prediction failed: %s", exc)
        return None
